# Generated by Django 5.2.7 on 2025-10-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMyJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('descrpition', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
